name: CI

on:
  push:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
    - run: gem install -N git-pr-release
    - run: git remote set-url origin https://$GIT_PR_RELEASE_TOKEN:x-oauth-basic@github.com/$GITHUB_REPOSITORY.git
    - run: git-pr-release --no-fetch
      env:
        GIT_PR_RELEASE_TOKEN: ${{ secrets.GIT_PR_RELEASE_TOKEN }}
